#: __init__.py:97
msgid "NextGIS geoinformation system"
msgstr "Servicio geoinformativo NextGIS"

#: __init__.py:219
msgid "Linux kernel"
msgstr "Núcleo Linux"

#: __init__.py:222
msgid "OS distribution"
msgstr "OS distribución"

#: __init__.py:234
msgid "CPU"
msgstr "CPU"

#: __init__.py:238
msgid "RAM"
msgstr "RAM"

#: exception.py:90
msgid "Validation error"
msgstr "Error de validación"

#: exception.py:95
msgid "Forbidden"
msgstr "Prohibido"

#: exception.py:100
msgid "Insufficient permissions"
msgstr "Permisos insuficientes"

#: exception.py:105
msgid "Operational error"
msgstr "Error operacional"

#: exception.py:110
msgid "External service error"
msgstr "Error de servicio externo"

#: storage.py:222
msgid "Estimation is already running"
msgstr "Estimación ya se está ejecutando"

#: test/test_exception.py:75
#, python-format
msgid "The answer is %d"
msgstr "La respuesta es %d"

