#: __init__.py:97
msgid "NextGIS geoinformation system"
msgstr ""

#: __init__.py:219
msgid "Linux kernel"
msgstr ""

#: __init__.py:222
msgid "OS distribution"
msgstr ""

#: __init__.py:234
msgid "CPU"
msgstr "CPU"

#: __init__.py:238
msgid "RAM"
msgstr ""

#: exception.py:90
msgid "Validation error"
msgstr ""

#: exception.py:95
msgid "Forbidden"
msgstr ""

#: exception.py:100
msgid "Insufficient permissions"
msgstr ""

#: exception.py:105
msgid "Operational error"
msgstr ""

#: exception.py:110
msgid "External service error"
msgstr ""

#: storage.py:222
msgid "Estimation is already running"
msgstr ""

#: test/test_exception.py:75
#, python-format
msgid "The answer is %d"
msgstr ""

